version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/client:
         working_directory: react-client
         run: npm install
         wait-on: 'http://localhost:3000'

      - cypress/server:
          working_directory: express-server
          run: npm install

      - cypress/run:
         post-steps:
            - store_test_results:
                path: cypress/results


