# Javascript Node 8 simple CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# Put this file in a .circleci/ folder
version: 2


jobs:
  build_test:
    docker:
      # specify the version you desire here
      - image: joincolony/circleci-cypress

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/devops-boilerplate

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install client dependencies
          command: cd react-client && npm install

      - run:
          name: Install server dependencies
          command: cd express-server && yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run Cypress Tests!
          command: cd react-client && npm test

  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "5a:17:77:cd:28:f4:8a:ca:7d:b0:bd:cf:ec:a1:20:d2"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:devops-boilerplate.git HEAD:refs/heads/master
            heroku run node index.js
            heroku restart
  workflows:
    version: 2
    build_test:
      jobs:
        - build_test
        - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: master