version: 2.1

jobs:
  api:
    docker:
      - image: circleci/node:10.8.0

    working_directory: ~/devops-boilerplate/
    steps:
      - checkout
      - run: cd devops-boilerplate/express-server && npm install
      - run: cd devops-boilerplate/express-server && npm run build
      - run: cd devops-boilerplate/express-server && npm start

  client:
    docker:
      - image: cypress/base:8

    working_directory: ~/devops-boilerplate/
    steps:
      - checkout
      - run: cd devops-boilerplate/react-client && npm install
      - run: cd devops-boilerplate/react-client && npm run build
      - run: cd devops-boilerplate/react-client && npm test


  workflows:
    version: 2
    concurrently:
      jobs:
        - api
        - client
    build-and-deploy:
      jobs:
        - checkout_code
        - client:
          requires:
            - checkout_code
        - api:
          - requires:
            - checkout_code
        - cypress/run:
          requires:
            - cypress/install