version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/devops # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose down -v && docker-compose up --build
      - run:
           name: "Verify Build Status"
           command: if echo $ = 0; then echo "Build passed buddy."; exit 0; fi
           when: always