version: 2

jobs:
  checkout_code:
    build:
      machine: true # Use a Linux VM instead of docker environment
      working_directory: ~/devops # Default working directory, where your project will be cloned
      steps:
        - checkout
        - save_cache:
              key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
              paths:
                - ~/devops
  deploy:
    machine:
      enabled: true
    working_directory: ~/devops
    environment:
      - HEROKU_APP: devops-boilerplate
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/devops-boilerplate.git master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - cypress_test:
          requires:
            - bundle_dependencies
            - docker-compose up
      - deploy:
          requires:
            - cypress_test