# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# Put this file in a .circleci/ folder
version: 2


jobs:
  build_test:
    docker:
      # specify the version you desire here
      - image: joincolony/circleci-cypress

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/devops-boilerplate

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install client dependencies
          command: cd react-client && npm install

      - run:
          name: Install server dependencies
          command: cd express-server && yarn && yarn start
          background: true

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run Cypress Tests!
          start: cd react-client && npm start && cd express-server && yarn start
          wait-on: 'http://localhost:3000'
          command: cd react-client && npm start

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:31f9c0bf-49d7-43e0-8672-aa3b85833693@git.heroku.com/devops-boilerplate.git master

workflows:
  version: 2
  build:
    jobs:
      - build_test
      - deploy:
            requires:
              - build_test
            filters:
              branches:
                only: master