version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/devops # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: |
       set -x
      docker-compose up -d
      docker run --network container:devops \
        appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused
      http://localhost:3000/contacts/test