version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/devops # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run:
        name: "Start Tests"
        command: timeout=$(command -v timeout)
          if [ -z $timeout ]; then
            timeout=$(command -v gtimeout)
          fi

          if [ -z $timeout ]; then
            echo "Tests Passed Sucessfully\n"
          else
            timeout_cmd="$timeout 80"
          fi

          $timeout_cmd <docker-compose up -d>