version: 2
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/devops # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: |
      TAG=$DOCKER_TAG
      docker-compose down -v && docker-compose up --build
        if [[ ((`echo $CIRCLE_BRANCH | grep -c "master"` > 0))]]; then
          echo "Push to registry since it's the master branch."
        else
          echo "Skip Docker push image since it is not the master branch."
        fi