version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  react: thefrontside/react@0.1.0
workflows:
  push:
    jobs:
      client:
        - working_directory: ~/devops-boilerplate/
        - react/install
        - react/test:
            requires:
              - cd react-client react/install

      api:
        - working_directory: ~/devops-boilerplate/
        - cd express-server npm install

  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'
          no-workspace: true