version: 2.1
jobs:
  orbs:
    cypress: cypress-io/cypress@1
workflows:
  build: 'Install dependencies checkout code'
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/devops # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose down -v && docker-compose up --build
    build: 'execute e2e tests'
      jobs:
        # install dependencies first (on 1 machine)
        - cypress/install
        # now run tests
        - cypress/run:
            # give this job a custom name for clarity
            name: 'end-to-end tests'
            requires:
              # use previously installed dependencies
              # to avoid installing them on each machine running tests
              - cypress/install
            record: true # record results to Cypress Dashboard
          - store_artifacts:
              path: ~/devops/features/fail-screenshots