version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  react: thefrontside/react@0.1.0
workflows:
  push:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
  build:
    jobs:
      - cypress/run:
          working_directory: ~/devops-boilerplate/
          yarn: false
          start: cd react-client npm start
          wait-on: 'http://localhost:3000'
          no-workspace: true